### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by thechipsss** [TheYoBots/YoBot_Bronze#2]
@TheYoBots  sorry as I can't talk to you in lichess I want to ask a question when I send logs you edit so how do I make logs as ur

**Comment by TheYoBots** [comment]
Sorry I don't understand what you are trying to say.

**Comment by thechipsss** [comment]
https://github.com/OIVAS7572/lichess-bot/issues/60 like here you edited 1# so how did you did that?

**Comment by TheYoBots** [comment]
Use quotes ``

**Comment by thechipsss** [comment]
Oh
